name: Run Gradle Build

on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    outputs:
      commit-number: ${{ steps.commit-count.outputs.commit-number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Calculate commit number
        id: commit-count
        run: echo "commit-number=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew clean build
      - name: Process built JARs
        run: |
          mkdir -p build/processed
          for jar in build/versions/*.jar; do
            if [[ ! "$jar" == *"dev"* ]]; then
              filename=$(basename "$jar")
              version=$(echo "$filename" | grep -o '1\.21\.[0-9]\+')
              new_name="zen-${version}-fabric-nightly-${{ steps.commit-count.outputs.commit-number }}.jar"
              cp "$jar" "build/processed/$new_name"
            fi
          done
      - name: Upload built mod JARs
        uses: actions/upload-artifact@v4.3.0
        with:
          name: zen-fabric-nightly-${{ steps.commit-count.outputs.commit-number }}
          path: build/processed/*.jar

  send-to-discord:
    if: github.event_name == 'push'
    needs: gradle
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK }}
      COMMIT_NUMBER: ${{ needs.gradle.outputs.commit-number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Send nightly.link to Discord
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${COMMIT_HASH}"
          NIGHTLY_LINK="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/zen-fabric-nightly-${COMMIT_NUMBER}.zip"
          
          EMBED_PAYLOAD=$(jq -n \
            --arg title "Zen 1.21 nightly release" \
            --arg commit "**Latest Commit:** [$COMMIT_MESSAGE]($COMMIT_URL)" \
            --arg build "**Build:** #${COMMIT_NUMBER}" \
            --arg download "**Download:** [📦 zen-1.21-fabric-nightly-${COMMIT_NUMBER}.zip]($NIGHTLY_LINK)" \
            --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.000Z)" \
            '{
              embeds: [{
                title: $title,
                description: ($commit + "\n" + $build + "\n" + $download),
                color: 3447003,
                timestamp: $timestamp,
                footer: {
                  text: "Zen Fabric Nightly"
                }
              }]
            }')
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$EMBED_PAYLOAD" \
            "$DISCORD_WEBHOOK_URL"